Final Commit

diff --git a/.github/workflows/compile-java-application.yml b/.github/workflows/compile-java-application.yml
--- a/.github/workflows/compile-java-application.yml
+++ b/.github/workflows/compile-java-application.yml
@@ -32,28 +32,6 @@ jobs:
               name: java-build-artifact
               path: target/*.jar
 
-          #   If You want to use DockerHub use below code.
-          #   =============================================
-          # - name: Docker Login
-          #   uses: docker/login-action@v3
-          #   with:
-          #     username: ${{ vars.DOCKERHUB_USERNAME }}
-          #     password: ${{ secrets.DOCKERHUB_TOKEN }}
-          # - name: Enable QEMU
-          #   uses: docker/setup-qemu-action@v3
-      
-          # - name: Set up Docker Buildx
-          #   uses: docker/setup-buildx-action@v3
-      
-          # - name: Build and Push Docker Images with Retry
-          #   uses: docker/build-push-action@v6
-          #   with:
-          #     context: .
-          #     file: Dockerfile
-          #     tags: waghangad/spring-java-eks:latest
-          #     push: true
-          #     platforms: linux/amd64,linux/arm64
-
     Test-Application:
       runs-on: ubuntu-latest
       needs: Build-Application
@@ -68,7 +46,7 @@ jobs:
       - name: run test cases
         run: mvn test
 
-    Build-Push-Image:
+    Build-Image-And-Push:
       runs-on: ubuntu-latest
       needs: Test-Application
       steps:
@@ -104,42 +82,62 @@ jobs:
           docker tag $REGISTRY/$REPOSITORY $REGISTRY/$REPOSITORY:$IMAGE_TAG
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
 
-    # Dev-Deployment:
-    #   if: contains(github.ref, 'development') 
-    #   needs: Test-Application
-    #   runs-on: ubuntu-latest
-    #   environment:
-    #     name: development
-    #   steps:
-    #       - name: Checkout Code
-    #         uses: actions/checkout@v4
+    #   If You want to use DockerHub use below code.
+    #   =============================================
+    # - name: Docker Login
+    #   uses: docker/login-action@v3
+    #   with:
+    #     username: ${{ vars.DOCKERHUB_USERNAME }}
+    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
+    # - name: Enable QEMU
+    #   uses: docker/setup-qemu-action@v3
 
-    #       - name: Install kubectl
-    #         uses: azure/setup-kubectl@v4
+    # - name: Set up Docker Buildx
+    #   uses: docker/setup-buildx-action@v3
 
-    #       - name: Configure AWS Credentials
-    #         uses: aws-actions/configure-aws-credentials@v4
-    #         with:
-    #           audience: sts.amazonaws.com
-    #           aws-region: ap-south-1
-    #           role-to-assume: arn:aws:iam::992293216837:role/github-action-oidc-Role-xta7NbBBHjdI
+    # - name: Build and Push Docker Images with Retry
+    #   uses: docker/build-push-action@v6
+    #   with:
+    #     context: .
+    #     file: Dockerfile
+    #     tags: waghangad/spring-java-eks:latest
+    #     push: true
+    #     platforms: linux/amd64,linux/arm64
+
+    Dev-Deployment:
+      if: contains(github.ref, 'development') 
+      needs: Build-Image-And-Push
+      runs-on: ubuntu-latest
+      environment:
+        name: development
+      steps:
+          - name: Checkout Code
+            uses: actions/checkout@v4
+
+          - name: Install kubectl
+            uses: azure/setup-kubectl@v4
+
+          - name: Configure AWS Credentials
+            uses: aws-actions/configure-aws-credentials@v4
+            with:
+              audience: sts.amazonaws.com
+              aws-region: ap-south-1
+              role-to-assume: arn:aws:iam::992293216837:role/github-action-oidc-Role-xta7NbBBHjdI
         
-    #       - name: Update kubeconfig for EKS
-    #         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}
+          - name: Update kubeconfig for EKS
+            run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}
 
-    #       - name: Run k8s command
-    #         run: |
-    #           helm uninstall demoapp || true 
-    #           helm install demoapp helm-chart/ || true
-    #           # kubectl create -f service.yml
-    #           # kubectl create -f deployment.yml
-    #           # kubectl set image deployment/my-spring-boot-app my-spring-boot-app=992293216837.dkr.ecr.ap-south-1.amazonaws.com/study/demo-repo:$IMAGE_TAG        
-
-
+          - name: Run k8s command
+            run: |
+              helm uninstall demoapp || true 
+              helm install demoapp helm-chart/ || true
+              # kubectl create -f service.yml
+              # kubectl create -f deployment.yml
+              # kubectl set image deployment/my-spring-boot-app my-spring-boot-app=992293216837.dkr.ecr.ap-south-1.amazonaws.com/study/demo-repo:$IMAGE_TAG        
 
     Prod-Deployment:
       if: github.ref == 'refs/heads/main'
-      needs: Build-Push-Image
+      needs: Build-Image-And-Push
       runs-on: ubuntu-latest
       environment:
         name: production
